pass/urls.py
from django.urls import path
from . import views

urlpatterns = [
  # path('',VistaPaginaHome.as_view(), name='home'),
  path('',views.login, name='login')

]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings #para las imagenes
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',TemplateView.as_view(template_name="home.html")),
    path('', include('pass.urls')),
    path('articulos/', include('articulos.urls')),
    path('paginas/',   include('paginas.urls')),
    path('cuentas/',include('django.contrib.auth.urls')),
    path('cuentas/', include('cuentas.urls')),
    path('', include('paypal.standard.ipn.urls')),



    

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #Le decimos a django donde busque las imagenes

articulos/models.py
import uuid
from django.db import models
from django.conf import settings
from django.urls import reverse
#cada vez que se modifica un modelo se tiene que hacer la migracion
# Create your models here.
class Articulo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    artista = models.CharField(max_length=50, null=True)
    titulo = models.CharField(max_length=255)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    genero = models.CharField(max_length=20, blank=True)
    categoria = models.CharField(max_length=20, blank=True)
    imagen = models.ImageField(blank=True, null=True)
    costo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    tracklist = models.CharField(max_length=255, null=True)
    fecha_creacion = models.DateField(null=True)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse("detalle_articulo", args=[str(self.id)])
# class Articulo(models.Model):
#     artista =models.CharField(max_length=50, null=True)
#     titulo=models.CharField(max_length=255)
#     cuerpo=models.TextField()
#     fecha= models.DateTimeField(auto_now_add=True)
#     genero = models.CharField(max_length=20, blank=True)#nuevo
#     categoria = models.CharField(max_length=20,blank=True) 
#     imagen = models.ImageField(blank=True,null=True)
#     costo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
#     tracklist = models.CharField(max_length=255,null=True)
#     fecha_creacion = models.DateField(null=True)

#     def __str__(self):
#         return self.titulo
    
#     #vistas dinamicas
#     def get_absolute_url(self):
#             #cargar la url apartir del nombre
#         return reverse("detalle_articulo", kwargs={"pk": self.pk})
    
class Comentario(models.Model):
    Articulo=models.ForeignKey(Articulo,on_delete=models.CASCADE)
    comentario=models.CharField(max_length=140)
    autor=models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.comentario
    
    #caudno creamos un comentario nos lleva a esta url
    def get_absolute_url(self):
        return reverse("lista_articulos")

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TecGames</title>

    <!-- Agrega la referencia a tu archivo de estilos CSS aquí -->   
    <link rel="stylesheet" href="{% static 'base.css' %}">      
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body class="bg-dark text-light">

    <header class="p-3 mb-4 border-bottom">
        <!-- contenedor del titulo -->
        <div class="container-fuid bg-success rounded"  style="padding-top: 20px; padding-bottom: 20px;">
            <a href="/"  class="navbar-brand">
            <span class="h2 text-white">AMAZON</span>
            <span class="h4 text-white">music </span>

            <div class = "container">
                 <ul class = "mb-3" >
                    <li><a class="btn btn-outline-light" href="/">Inicio</a></li>
                    <li><a class="btn btn-outline-light" href="/articulos/">Albums</a></li>
                    <li><a class="btn btn-outline-light" href="/articulos/categorias">Categorías</a></li>
                    {% if user.is_authenticated %}
                    {% if not user.socialaccount_set.all %}
                        <!-- El usuario está autenticado pero no tiene una cuenta social -->
                        <li><a class="btn btn-outline-light" href="{% url 'logout' %}">Cerrar sesión</a></li>
                    {% else %}
                        <!-- El usuario está autenticado y tiene una cuenta social -->
                        <li><a class="btn btn-outline-light" href="{% url 'logout' %}">Cerrar sesión</a></li>
                    {% endif %}
                {% else %}
                    <!-- Contenido para usuarios no autenticados -->
                    <li><a class="btn btn-outline-light" href="{% url 'login' %}">Iniciar sesión</a></li>
                {% endif %}


                    {% comment %} <li><a class="btn btn-outline-light" href="{% url 'signup' %}">Registrarse en el sitio</a> {% endcomment %}
                    </li>
                    {% if user.is_staff %}
                    <li><a class="btn btn-outline-light" href="/articulos/nuevo">Agregar</a></li>
                    {% endif %}
                    {% comment %} {% if user.is_authenticated %}
                    <a class="btn btn-outline-light" href="{% url 'account_logout' %}">Logout</a>
                    {% endif %} {% endcomment %}
                </ul> 
                
            </div>
        
        </div>
    </header>

   
    
    {% block contenido %}

    

    {% endblock contenido %}

    {% include 'footer.html' %}
    
</body>
</html>

templates/acercade.html
{% extends "_base.html"%}
{% load static %}

{% block contenido %}

<h1>Empresa orgullosamente lagunera, creada y dirigida por Omar Tapia</h1>

{% endblock contenido %}

templates/agregar_comentario.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block contenido %}

<div>
<h4>Agregar un comentario</h4>
    <form action="" method="post">{% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success ml-2" type="submit">Guardar</button><!--con esto ya añadimos a detalle articculo lo de agregar comentario -->
    </form>
</div>
    <h4>Comentarios</h4>
{% endblock contenido %}

templates/detalle_articulo.html
<!--templates/detalle_articulo.html-->
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block titulo %} {{ object.titulo }} {% endblock titulo %}
{% block contenido %}

<div class="article-entry">
    <h2>{{object.artista}}</h2>
    <h2>{{object.titulo}}</h2>
   <h2><div> <a class="btn btn-outline-danger" href="{% url 'lista_articulos_por_genero' genero=object.genero %}">{{object.genero}}</a> 
   {% comment %} <h2><div> <a class="btn btn-outline-danger" href="{% url 'lista_articulos_artista' artista=object.artista %}">{{object.artista}}</a>  {% endcomment %}

    {% if object.categoria %}
  <a class="btn btn-outline-danger"  href="{% url 'lista_articulos_por_categoria' categoria=object.categoria%}">{{object.categoria}}</a>
   </div> </h2>
   {% endif %}
   
   {% if object.imagen %}
   <div style="text-align: center;">
       <img src="{{ object.imagen.url }}" alt="image" style="width: 300px; height: auto;">
   </div>
   
   {% endif %}


   <p text-align="center" class="text-light"><h2>{{object.costo}}$</h2></p>
   <hr>
   <p style="text-align: center; font-size: 16px;" class="text-light">{{ object.cuerpo }}</p>

  
   <hr>
    {% comment %} <p style="text-align: center; font-size: 16px;" >{{object.fecha}}</p> {% endcomment %}
    <p style="text-align: center; font-size: 16px;" >Lanzamiento : {{object.fecha_creacion}}</p>


    <div class="article-entry">
        <h4>Tracklist del album</h4>
        <div class="login-container ">
            <div class="welcome-message bg-dark text-dark">
              <p style="text-align: center; font-size: 16px;">{{object.tracklist}}
    
              </p>
              <nav></nav>
            </div>
            
    
          </div>
       
    </div>
    

    <p text-align="center" > <a href="{% url 'lista_articulos' %}" class="btn btn-outline-white">Volver</a>
     {% if user.is_staff %} 
    <a href="{% url 'editar_articulo' object.pk %}" class="btn btn-outline-white btn-primary">Editar</a>
    <a href="{% url 'eliminar_articulo' object.pk %}" class="btn btn-outline-white btn-danger">Eliminar</a> </p>
     {% endif %}</p>
</div>


{% if user.is_authenticated or user.socialaccount_set.all %}
<div class="login-container ">


   <!--{{ paypal.render }}-->
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AQUIVAELNUMERODECEUNTADEPAYPALSANDBOX&currency=MXN"></script>
    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Call your server to set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            
                            value: {{object.costo}},
                            
                        }
                    }]
                });
            },

            // Call your server to finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {

                    alert('transaction completed by ' + details.payer.name.given_name);
                });
            }

        }).render('#paypal-button-container');
    </script>
</div>
{% endif %}

{% if user.is_authenticated %}
<div>
<hr>
    <h4>Agregar un comentario</h4>
    <form method="post">
        
        {% csrf_token %}
        {{ form|crispy }}       
    <hr>
        <button class="btn btn-success ml-2" type="submit">Guardar</button><!--con esto ya añadimos a detalle articulo lo de agregar comentario -->
    </form>


    <h4 > <p text-algin="center">Comentarios</p></h4>
</div>
{% endif %}


    {% for comentario in object.comentario_set.all %}
    <p style="text-align: center; font-size: 16px;">{{ comentario.autor }} &middot; {{ comentario }}</p>
    {% endfor %}
{% endblock contenido %}

templates/editar_articulo.html
{% extends '_base.html' %}
{% block contenido %}
{% load crispy_forms_tags %}
<!-- <div class="article-entry">
    <h2>{{object.titulo}}</h2>
    <p>por {{object.autor}} | {{object.fecha}}</p>
    <p>{{object.cuerpo}}</p>
</div> -->
<form action="" method="post">{% csrf_token %}
    {{ form|crispy}}
    
    <input class="btn btn-info ml-2" type="submit" value="Modificar">
    <a href="{% url 'lista_articulos' %}" class="btn btn-info ml-2">Cancelar</a>

    </form>

<!-- <p><a href="{% url 'lista_articulos' %}">Modificar</a> | <a href="#">Eliminar</a></p>
<p>Volver a <a href="{% url 'lista_articulos' %}">Todos los articulos</a></p> -->
{% endblock contenido %}

templates/eliminar_articulo.html
<!--templates/eliminar_publicacion-->
{% extends '_base.html' %}
{% block contenido %}
{% load crispy_forms_tags %}

<h1>Eliminar entrada </h1>
<form action="" method="post">{% csrf_token %}
    <p>Esta completamente seguro que desea eliminar '<b>{{object.titulo}}</b>'</p>
    <button class="btn btn-info ml-2" type="submit">Confirmar</button>
    <a href="{% url 'lista_articulos' %}" class="btn btn-info ml-2">Cancelar</a>
</form>
{% endblock contenido %}

templates/footer.html
<!-- templates/footer.html -->
{% load static %}
<footer class="bg-success text-white py-5 mt-5"> <!-- Añadido mt-5 para agregar espacio superior -->
    <div class="container">
        <div class="row">
            <div class="col-lg-6 text-center">
                <h3 class="mb-4">Redes Sociales</h3>
                <a href="https://open.spotify.com/intl-es?" target="_blank" rel="noopener" class="btn btn-outline-dark me-2">
                    <img src="{% static 'spotify.png' %}" alt="Spotify" class="img-fluid">
                </a>
                
                <a href="https://twitter.com/?lang=es" target="_blank" rel="noopener" class="btn btn-outline-dark me-2">
                    <img src="{% static 'x.png' %}" alt="Twitter" class="img-fluid">
                </a>
                
                <a href="https://www.instagram.com/" target="_blank" rel="noopener" class="btn btn-outline-dark">
                    <img src="{% static 'facebook.png' %}" alt="Instagram" class="img-fluid">
                </a>
                
            </div>
            <div class="col-lg-6">
                <div class="text-center">
                    <h4 class="mb-4">Disfruta de lo que más te gusta</h4>
                    <p style="text-align: center; font-size: 10px;">Derechos reservados &copy; ©2020-2023 Todos los derechos reservados. AmazomMusic® es una marca registrada de The Rocket Science Group.
                         Apple y su logotipo son marcas comerciales. 
                         Privacidad | Condiciones | Normativa | Preferencias de cookies</p>
                </div>
            </div>
        </div>
    </div>
        <!-- Copyright section of the footer-->
 <div class="py-4 fw-light  text-gray-300" style="background-color: #1e1e1e !important;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-6 text-center text-md-start">
          <p class="mb-md-0">&copy; {{ year }} Mi tienda. Todos los derechos reservados.</p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline mb-0 mt-2 mt-md-0 text-center text-md-end">
            <li class="list-inline-item"><img class="w-50" src="https://d19m59y37dris4.cloudfront.net/sell/2-0/img/visa.svg" alt="..."></li>
            <li class="list-inline-item"><img class="w-50" src="https://d19m59y37dris4.cloudfront.net/sell/2-0/img/mastercard.svg" alt="..."></li>
            <li class="list-inline-item"><img class="w-50" src="https://d19m59y37dris4.cloudfront.net/sell/2-0/img/paypal.svg" alt="..."></li>
            <li class="list-inline-item"><img class="w-50" src="https://d19m59y37dris4.cloudfront.net/sell/2-0/img/western-union.svg" alt="..."></li>
          </ul>
        </div>
      </div>
    </div>
  </div> 
</footer> 

templates/home.html
{% extends '_base.html' %}
{% load static %}
{% comment %} {% load socialaccount %} {% endcomment %}

{% block contenido %}
{% comment %} {% providers_media_js %} {% endcomment %}

<div class="home">
  <section>
    <div class="container-fluid">
      <div class="row">

        <div class="col-lg-6 dark-overlay split-screen-column align-items-center align-items-lg-end" style="background-image: url(https://badomensofficial.com/cdn/shop/t/29/assets/bo-footer-promo-p-1600.png?v=156528871753265248431684784513); background-color: #d2cecb; background-size: cover; background-position: center;"> 
          <div class="overlay-content py-6 mt-6 px-lg-5 mt-lg-0 mb-lg-5">
            <h1 class="display-3 mb-4 text-white fw-bold split-screen-heading letter-spacing-1">Obtener la musica que mas te gusta</h1>
            <p class="lead mb-4"></p>
            <p> <a class="btn btn-light mx-1 mb-1" href="/articulos/">Ver coleccion</a><a class="btn btn-outline-light mx-1 mb-1" href="/articulos/categorias">Categorias</a></p>
          </div>
          
        </div>
  
         <div class="col-lg-6 dark-overlay split-screen-column align-items-center align-items-lg-end" style="background-image: url(https://badomensofficial.com/cdn/shop/files/FindingGod2.png?v=1689195592); background-color: #d2cecb; background-size: cover; background-position: center;"> 
          <div class="overlay-content py-6 mt-6 px-lg-5 mt-lg-0 mb-lg-5">
            <h1 class="display-3 mb-4 text-white fw-bold split-screen-heading letter-spacing-1">Vinyl</h1>
            <p class="lead mb-4"></p>
            <p> <a class="btn btn-light mx-1 mb-1" href="/articulos/">ver coleccion</a><a class="btn btn-outline-light mx-1 mb-1" href="/articulos/categorias">Categorias</a></p>
          </div>
        </div> 
  
         <div class="col-lg-6 dark-overlay split-screen-column align-items-center align-items-lg-end" style="background-image: url(https://badomensofficial.com/cdn/shop/files/FindingGod2.png?v=1689195592); background-color: #d2cecb; background-size: cover; background-position: center;"> 
          <div class="overlay-content py-6 mt-6 px-lg-5 mt-lg-0 mb-lg-5">
            <h1 class="display-3 mb-4 text-white fw-bold split-screen-heading letter-spacing-1">CD</h1>
            <p class="lead mb-4"></p>
            <p> <a class="btn btn-light mx-1 mb-1" href="/articulos/">ver coleccion</a><a class="btn btn-outline-light mx-1 mb-1" href="/articulos/categorias">Categorias</a></p>
          </div>
          
        </div> 
        <!--https://d19m59y37dris4.cloudfront.net/sell/2-0/img/photo/ian-dooley-347962-unsplash.jpg-->
         <div class="col-lg-6 split-screen-column align-items-center align-items-lg-end" style="background-image: url(https://www.linkinpark.com/sites/g/files/g2000015666/files/styles/merch_image_600_600/public/2019-04/albums-featured.jpeg?itok=TtL4XjHf); background-color: #e5b6b4; background-size: cover; background-position: center;"> 
          <div class="py-6 px-lg-5 mb-lg-5">
            <h1 class="display-3 mb-4 text-white fw-bold split-screen-heading letter-spacing-1">De tus artistas favoritos</h1>
            <p class="lead mb-4"></p>
            <p> <a class="btn btn-light mx-1 mb-1" href="/articulos/">Ver coleccion</a><a class="btn btn-outline-light mx-1 mb-1" href="/articulos/categorias">Categorias</a></p>
          </div>
        </div>  
      </div>
    </div>
  </section>  
  
</div>




<div class = "home">
  <section>
    <section class="py-6 bg-gray-100">
      <div class="container">
       <div class="row">
          <div class="col-xl-8 mx-auto text-center mb-5">
            <h1>Categorias</h1>
            <p class="lead text-muted"></p>
          </div>
        </div> 
    
         <div class="row">
          <div class="col-md-6 d-flex align-items-md-stretch mb-4 mb-md-0">
            <div class="d-flex align-items-center text-white dark-overlay w-100 text-center py-6 py-md-0" style="background: center center url(https://redhotchilipeppers.com/assets/img/tour-dates-slide-7.jpg) no-repeat; background-size: cover);"><a class="tile-link" href="category.html"> </a>
              {% comment %} <div class="card-img-overlay w-100 overlay-content">
              <h2 class="display-2 fw-bold text-uppercase mb-0">Rock</h2> 
              </div> {% endcomment %}
              <h2 class="display-2 fw-bold text-uppercase mb-0">Rock</h2> 

    
            </div>
          </div>
          <div class="col-md-6">
            <div class="card border-0 text-white text-center mb-4 dark-overlay"> <img class="card-img" src="https://www.drdre.com/files/2023/02/3200x1800-compressed-1536x835.jpg" alt="Ladies"><a class="tile-link" href="category.html"> </a>
              <div class="card-img-overlay d-flex align-items-center">
                <div class="text-center w-100 overlay-content">
                  <h2 class="display-4 fw-bold text-uppercase text-center mb-0">Hip Hop</h2>
                </div>
              </div>
            </div>
    
           <div class="card border-0 text-white text-center mb-4 dark-overlay"> <img class="card-img" src="https://badomensofficial.com/cdn/shop/t/34/assets/bo-footer-promo-p-1600.png?v=156528871753265248431698939694" alt="Ladies"><a class="tile-link" href="category.html"> </a>
              <div class="card-img-overlay d-flex align-items-center">
                <div class="text-center w-100 overlay-content">
                  <h2 class="display-4 fw-bold text-uppercase text-center mb-0"></h2>
                </div>
              </div>
            </div>
    
            <div class="card border-0 text-white text-center  dark-overlay"> <img class="card-img" src="https://store.taylorswift.com/cdn/shop/files/L2BkajKd7PGZm4HNdOvA_600x.png?v=1684773869" alt="Accessories"><a class="tile-link" href="category.html"> </a>
              <div class="card-img-overlay d-flex align-items-center">
                <div class="text-center w-100 overlay-content">
                  <h2 class="display-4 fw-bold text-uppercase text-center mb-0">Pop</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>
</div>

 
{% endblock contenido %}

templates/lista_articulos.html
<!-- articulos/lista_articulos -->
{% extends "_base.html" %}

{% load static %}
{% block titulo %}Articulos{% endblock titulo %}
{% block contenido %}
{% comment %} <h1><p text-align="center">Articulos</p></h1> {% endcomment %}
<hr>
{% comment %} <h2>Bienvenido{{user.username}}</h2> {% endcomment %}
    <div class="row">
        {% for articulo in articulo_list %}
            <div class="col-md-3"  >
                <div class="card mb-3 bg-dark text-light">
                    <div class="card-header text-light">
                        <h2 class="font-weight-bold link-white text-light text-truncate">
                            <a href="{% url 'detalle_articulo' pk=articulo.id %}"  class="navbar-brand">
                                {{ articulo.titulo }}
                            </a>
                        </h2>
                        <h6 class="text-muted"><p class="text-light"text-align="center">{{ articulo.categoria }} | {{ articulo.genero }} | {{ articulo.fecha_creacion }}</p></h6>
                    </div>
                    <div class="card-body">
                    {% if articulo.imagen %}
                        <div style="text-align: center;" >
                         <a  class="text-light" href="{% url 'detalle_articulo' articulo.pk %}"> <img src="{{ articulo.imagen.url }}" alt="image" style="width: 300px; height: auto;"> </a>
                        </div>
                     {% endif %}
                       <p text-align="center" class="text-light" > {{ articulo.costo }}</p>
                    </div>
              
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock contenido %}

templates/lista_articulos_artistas.html
<!-- templates/lista_articulos_por_categoria.html admin -->
{% extends "_base.html" %}

{% load static %}

{% block titulo %}Articulos por Categoría{% endblock titulo %}

{% block contenido %}

<h2></h2>
<div class="row">
    {% for articulo in articulo_list %}
        <div class="col-md-3">
            <div class="card mb-3 bg-dark" >
                <div class="card-header">
                    <h1 class="font-weight-bold text-light text-truncate">
                        <a href="{% url 'detalle_articulo' articulo.pk %}" class="navbar-brand" class="text-light">
                            {{ articulo.titulo }}
                        </a>
                    </h1>
                    <h6 class="text-muted" class="text-light"><p class="text-light" text-align="center">{{ articulo.categoria }} | {{ articulo.genero }} | {{ articulo.fecha }}</p></h6>
                </div>
                <div class="card-body">
                    {% if articulo.imagen %}
                        <div style="text-align: center;" class="text-light">
                            <a href="{% url 'detalle_articulo' articulo.pk %}"> <img src="{{ articulo.imagen.url }}" alt="image" style="width: 300px; height: auto;"> </a>
                        </div>
                    {% endif %}
                    <p text-align="center" class="text-light"> {{articulo.costo}}$</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock contenido %}

templates/lista_articulos_por_categoria.html
<!-- templates/lista_articulos_por_categoria.html admin -->
{% extends "_base.html" %}

{% load static %}

{% block titulo %}Articulos por Categoría{% endblock titulo %}

{% block contenido %}

<h2></h2>
<div class="row">
    {% for articulo in articulo_list %}
        <div class="col-md-3">
            <div class="card mb-3 bg-dark" >
                <div class="card-header">
                    <h1 class="font-weight-bold text-light text-truncate">
                        <a href="{% url 'detalle_articulo' articulo.pk %}" class="navbar-brand" class="text-light">
                            {{ articulo.titulo }}
                        </a>
                    </h1>
                    <h6 class="text-muted" class="text-light"><p class="text-light" text-align="center">{{ articulo.categoria }} | {{ articulo.genero }} | {{ articulo.fecha }}</p></h6>
                </div>
                <div class="card-body">
                    {% if articulo.imagen %}
                        <div style="text-align: center;" class="text-light">
                            <a href="{% url 'detalle_articulo' articulo.pk %}"> <img src="{{ articulo.imagen.url }}" alt="image" style="width: 300px; height: auto;"> </a>
                        </div>
                    {% endif %}
                    <p text-align="center" class="text-light"> {{articulo.costo}}$</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock contenido %}

templates/lista_categorias.html
<!-- templates/lista_categorias.html -->
{% extends '_base.html' %}
{% load static %}

{% block titulo %}Categorías{% endblock titulo %}

{% block contenido %}

<div class="container-fluid" style="background-image: url(https://store.askingalexandria.com/cdn/shop/files/DESKTOP-HERO-02.jpg?v=1689360711&width=1500); background-size: cover; background-position: center; background-repeat: no-repeat; height: 50vh; position: relative;">
    <!-- Contenido adicional se puede agregar encima de la imagen -->
    <div class="text-center" style="position: absolute; top: 30%; left: 50%; transform: translate(-50%, -50%);">
        <h1>!Categorias!</h1>
        <p></p>  <ul>
 {% for categoria in categorias %}
    {% if categoria %}
        <li>
          <a class="btn btn-outline-dark bg-success" href="{% url 'lista_articulos_por_categoria' categoria=categoria %}">{{ categoria }}</a>
        </li>
    {% endif %}
{% endfor %} 


{% comment %} {% for artista in artistas %}
    {% if artista %}
        <li>
          <a class="btn btn-outline-dark bg-success" href="{% url 'lista_articulos_artista' artista=artista %}">{{ artista }}</a>
        </li>
    {% endif %}
{% endfor %}  {% endcomment %}

  </ul>
    </div>
</div>
{% endblock contenido %}

templates/login.html
{% extends '_base.html' %}
{% load static %}
{% load socialaccount %}

{% block contenido %}
{% providers_media_js %}

  


  <div class="login-container">
    {% if user.is_authenticated %}
    <div class="welcome-message">
      <p>¡Bienvenido, {{ user.username }} 😃!</p>
      <nav></nav>
    </div>
    {% else %}

    <h2>Iniciar sesión con Google</h2>
    <a href="{% provider_login_url 'google' %}" class="google-btn">
      <img src="{% static 'google.png' %}" alt="Google Icon">
      Iniciar sesión con Google
    </a>

    {% endif %}
  </div>
{% endblock contenido %}

templates/nuevo_articulo.html
<!--plantillas/nuevo_articulo-->
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block contenido %}

<h1>Nuevo Articulo</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}

    {{ form|crispy }}

    <button class="btn btn-success ml-2" type="submit">Guardar</button>
    <a href="{% url 'lista_articulos' %}" class="btn btn-info ml-2">Cancelar</a>

</form>
{% endblock contenido %}